---

version: "3"

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supers3cret
      MYSQL_DATABASE: redirect
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  webui:
    build: service/webui
    environment:
      PORT: 4000
      VIRTUAL_HOST: webui.docker
      VIRTUAL_PORT: 4000
      API_URL: http://api.docker
    volumes:
      - ./service/webui:/app

  api:
    build: service/api
    command: npm run watch
    depends_on:
      - mysql
    environment:
      PORT: 5000
      VIRTUAL_HOST: api.docker
      VIRTUAL_PORT: 5000
      DB_URL: mysql://root:supers3cret@mysql:3306/redirect
    volumes:
      - ./service/api:/app

  actor:
    build: service/api
    command: npm run watch
    depends_on:
      - mysql
    environment:
      PORT: 4010
      VIRTUAL_HOST: actor.docker
      VIRTUAL_PORT: 4010
      DB_URL: mysql://root:supers3cret@mysql:3306/redirect
    volumes:
      - ./service/actor:/app

volumes:
  mysql:
