version: "3"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supers3cret
      MYSQL_DATABASE: redirect
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  frontend:
    build: service/frontend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    volumes:
      - ./service/frontend/dist:/srv

volumes:
  mysql:
