version: "3"

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supers3cret
      MYSQL_DATABASE: redirect
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  frontend:
    build: service/frontend
    environment:
      PORT: 4000
      VIRTUAL_HOST: redirect.docker
      VIRTUAL_PORT: 4000
    volumes:
      - ./service/frontend/dist:/srv

  backend:
    build: service/backend
    command: npm run watch
    depends_on:
      - mysql
    environment:
      PORT: 5000
      VIRTUAL_HOST: api.redirect.docker
      VIRTUAL_PORT: 5000
      DB_URL: mysql://root:supers3cret@mysql:3306/redirect
    volumes:
      - ./service/backend:/app

volumes:
  mysql:
