---

name: Build docker images

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push redirect-actor
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "finwo/redirect-actor:latest,finwo/redirect-actor:${{ github.ref_name }}"
          platforms: 'linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          context: ./service/actor
          file: ./service/actor/Dockerfile

      - name: Build and push redirect-api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "finwo/redirect-api:latest,finwo/redirect-api:${{ github.ref_name }}"
          platforms: 'linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          context: ./service/api
          file: ./service/api/Dockerfile

      - name: Build and push redirect-webui
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "finwo/redirect-ui:latest,finwo/redirect-ui:${{ github.ref_name }}"
          platforms: 'linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          context: ./service/webui
          file: ./service/webui/Dockerfile
